import RestLink from 'apollo-link-rest';

const restLink = new RestLink({
    uri: 'http://localhost:5000'
})




mutation CREATE_USER {
    user(input: $input) @rest(type: "User", path:"/user", method: "POST"){
        name
        email
        role
        password
    }
}